import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('didouttojutro-1120@yopmail.com');
  await page.getByRole('textbox', { name: 'Organisation Code' }).click();
  await page.getByRole('textbox', { name: 'Organisation Code' }).fill('ORG193');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('menuitem', { name: 'Workforce down' }).getByLabel('down').click();
  await page.getByRole('link', { name: 'Staff' }).click();
  await page.getByRole('button', { name: 'Add Staff' }).click();
  await page.locator('.ant-select-selection-item').first().click();
  await page.getByTitle('Mrs').locator('div').click();
  await page.getByRole('textbox', { name: '* First Name' }).click();
  await page.getByRole('textbox', { name: '* First Name' }).fill('fffghgjiu');
  await page.getByRole('textbox', { name: 'Last Names' }).click();
  await page.getByRole('textbox', { name: 'Last Names' }).fill('bkbb j');
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('jhvbn');
  await page.getByRole('combobox', { name: 'Gender' }).click();
  await page.getByTitle('Female').click();
  await page.locator('div:nth-child(4) > div > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .Select_Select__AxE1D > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByTitle('Ajeesh ').click();
  await page.getByText('Bhuvanesh').click();
  await page.locator('div:nth-child(4) > div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .Select_Select__AxE1D > .ant-select > .ant-select-selector').click();
  await page.getByText('Akan').click();
  await page.getByRole('textbox', { name: 'Date Of Birth' }).fill('1999-03-10');
  await page.getByRole('textbox', { name: 'Employee Code' }).click();
  await page.getByRole('textbox', { name: 'Employee Code' }).fill('2');
  await page.locator('#nest-messages_nationality').click();
  await page.getByText('Andorran').click();
  await page.getByRole('combobox', { name: 'Marital Status' }).click();
  await page.getByTitle('Married').click();
  await page.locator('div:nth-child(6) > div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .Select_Select__AxE1D > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByTitle('Anglican').click();
  await page.getByRole('textbox', { name: '* Email Address' }).click();
  await page.getByRole('textbox', { name: '* Email Address' }).fill('fgdf@gmailcom');
  await page.getByRole('textbox', { name: 'Work Number' }).click();
  await page.getByRole('textbox', { name: 'Work Number' }).fill('+61 (2) 4258 7456 25');
  await page.locator('div:nth-child(3) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .Select_Select__AxE1D > .ant-select > .ant-select-selector > .ant-select-selection-item').first().click();
  await page.getByText('(GMT+00:00) Azores Time').click();
  await page.getByRole('textbox', { name: '* Mobile' }).click();
  await page.getByRole('textbox', { name: '* Mobile' }).fill('+61 (2) 9424 7845 96');
  await page.locator('.w-full > div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .Select_Select__AxE1D > .ant-select > .ant-select-selector').click();
  await page.locator('div').filter({ hasText: /^Company Website Contact Form$/ }).first().click();
  await page.getByRole('textbox', { name: 'Tags or Labels' }).click();
  await page.getByRole('textbox', { name: 'Tags or Labels' }).fill('sdvgxfgf');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});